apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: roboshop
  labels:
    name: nginx
    project: roboshop
spec:
  containers:
  - name: nginx-image
    image: nginx
    ports:
    - containerPort: 80