apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-1
  region: us-east-1
managedNodeGroups:
  - name: cluster1-ng
    instanceTypes: ["m5.large","t3.small","t3.medium","c5.large"]
    desiredCapacity: 2  # if we don't give desired capacity, by default it will create 3 worked nodes
    spot: true
    
