apiVersion: v1
kind: Secret
metadata:
  name: pod-secret
type: Opaque
# data should be encoded using "echo ec2-user | base64"
# to decode data "echo "RGV2T3BzMzIxCg==" | base64 --decode"
data:
  username: "ZWMyLXVzZXIK"
  password: "RGV2T3BzMzIxCg=="

