apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod #podname here
  namespace: roboshop #in which name space we need to create
  labels: #used to select the pods "kubectl get pods -l project=roboshp"
    environment: prod
    project: roboshop

#what exactly we want to run in pod, we will define here  
spec:
  containers:
  - name: nginx-image
    image: nginx
    ports:
    - containerPort: 80