apiVersion: v1
kind: Pod
metadata:
  name: env-demo
spec:
  containers:
    - name: nginx-env
      image: nginx
      env:
      - name: course
        value: kubernetes
      - name: trainer
        value: suresh
